### ISSUE TITLE
CSS bug on hover in ListerPro

### ISSUE THREAD

**Issue by jmartsch** [noelboss/AdminThemeBoss#1]
First of all: ❤️ ❤️ ❤️ I love this theme ❤️ ❤️ ❤️ 

When I am hovering over a button in a ListerPro, the button disappears, because of this line:
```
.uk-table-divider>:first-child>tr:not(:first-child) :hover, .uk-table-divider>:not(:first-child)>tr :hover, .uk-table-divider>tr:not(:first-child) :hover {
     background: rgba(250,250,250,.95); 
}
```
Disabling the background and everything looks fine, at least in ListerPro.

**Comment by noelboss** [comment]
Thanks for the love.

I don't have lister pro installed. Would you consider sending me a login, or do you have a fix? is there a class arround lister pro that I could target?

Do you have a screenshot?

**Comment by noelboss** [comment]
0.4.0 should probably fix your issue…

**Comment by jmartsch** [comment]
Hey Noel, 0.4.0 fixed it. Thank you.
